# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yang's Site
logo: "/assets/images/88x88.png"
email:
description: >- # this means to ignore newlines until "baseurl:"
  A NOT boring site.
twitter_username: username
github_username: username
minimal_mistakes_skin: dark  #  "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise
search: true
teaser: /assets/images/500x300.png
words_per_minute         : 200
environment: production
comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
repository: "laserengineer/laserengineer.github.io"
github: [metadata]
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Yang Yu"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "A L&L (laser and LabVIEW) Engineer."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://laserengineer.github.io/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/laserengineeryu/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: false
      comments: true
      share: true
      header:
        image: /assets/images/laserspace.jpg #the image at the top of the page
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
      header:
        image: /assets/images/laserspace.jpg #the image at the top of the page
    values:
      layout: single
      author_profile: true
      comments: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
